### ISSUE TITLE
Container instances failing to resolve other azure resources

### ISSUE THREAD

**Issue by bmovva1991** [virtual-kubelet/azure-aci#163]
k8s version 1.20.7

We are experiencing an issue with the aks virtual kubelet since a few days. We deploy to aks using azure devops . When we deploy a new service . 

2021-09-24T23:27:11: PM2 log: Launching in no daemon mode
2021-09-24T23:27:11: PM2 log: App [index:0] starting in -fork mode-
2021-09-24T23:27:11: PM2 log: App [index:0] online
2021-09-24T23:27:14.396Z - info: Starting Scheduler for default dev
2021-09-24T23:27:19.530Z - critical: Error logging data: Starting Scheduler for default dev --PublisherError: Unable to send messages. Check the message configuration. getaddrinfo EAI_AGAIN evns-qa-pd.servicebus.windows.net
    at PublisherErrorHandler.getSendError (/app/node_modules/@be/publisher/lib/error-handler.js:26:16)
    at EventHubPublisher.sendMessage (/app/node_modules/@be/publisher/lib/publishers/event-hub-publisher.js:69:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: RequestError: Error: getaddrinfo EAI_AGAIN app-qa-api.azurewebsites.net
    at NantAPI._request (/app/node_modules/@hw/edge-sdks/lib/nant-api/NantAPI.js:153:15)
2021-09-24T23:40:00.005Z - info: Scheduling commands at xxx
2021-09-24T23:45:00.009Z - info: Scheduling occupancy_flow at xxx
2021-09-24T23:45:00.014Z - info: Scheduling occupancy_flow at xxx
2021-09-24T23:45:00.017Z - info: Scheduling occupancy_flow at xxx

If you observe it fails to resolve the other azure services endpoints when the service is started but after a few minutes it auto resolves and my service starts . 
but meantime because of this my ado release pipeline fails 
2021-09-24T23:36:01.0229020Z ##[error]Error: error: deployment "scheduler" exceeded its progress deadline

This happens randomly .

**Comment by feiskyer** [comment]
@bmovva1991 could you open a support ticket from Azure portal?

**Comment by bmovva1991** [comment]
@feiskyer Raised a ticket . thanks

**Comment by sebastianhutter** [comment]
Hijacking this issue ;-)

We see a similar behaviour but with Azure Application Insights.

We recently started integrating Application Insights in all our springboot services. On kubernetes it works well, as soon as we start ACIs via the virtual-kubelet the ACI Pod is unable to resolve the app insights endpoint.

```
13:09:38.920Z WARN  c.m.a.a.i.AppIdSupplier$GetAppIdTask - unable to retrieve appId exception sending request to https://northeurope-0.in.applicationinsights.azure.com/api/profiles/...../appId (future failures will be aggregated and logged once every 5 minutes)
```

Unfortunately, the application insights agent won't retry (as its a java agent loaded during application startup).
This basically means we are running blind when our jobs are executed in ACI via the virtual-kubelet.

@bmovva1991 where you able to resolve the problem? If so can you tell me how?

**Comment by helayoty** [comment]
@feiskyer @bmovva1991 would you please provide more logs if this issue still happens in the latest version?

**Comment by helayoty** [comment]
Closing as no response from the author. Please feel free to re-open it with more details/updates
